name: CI

env:
  environment: env_main

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      upload-coverage: true

  tag-latest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: semantic-release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    # if there were commits during previous steps
    # actions/checkout#1327
    # actions/checkout#461
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Run latest-tag
      uses: EndBug/latest-tag@v1.5.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  semantic-release:
    runs-on: windows-latest
    permissions:
      contents: write
      id-token: write
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-semantic-release==8.1.1 pyinstaller==6.0.0 pyqt5-tools==5.15.9.3.3
        pip install -r requirements.txt
    # to bypass protected branch rules:
    # https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html#example-workflow (warnings section)
    # https://github.com/python-semantic-release/python-semantic-release/issues/311
    - name: semantic-release
      run: |
        python -m semantic_release version
        python -m semantic_release publish
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}